spring:
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_ID:admin@admin.com}
    password: ${EMAIL_PASSWORD:password}
    properties:
      mail:
        mime:
          charset: utf-8
        smtp:
          write-timeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8
    verify:
      host: ${VERIFY_EMAIL_HOST:verify.myfitbody.co.kr}
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  jpa:
    open-in-view: false
server:
  port: ${SERVER_PORT:8080}
api:
  security:
    jwt:
      secret: ${JWT_SECRET:secret}
cors:
  origins: ${CORS_ORIGINS:*}
