spring:
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: utf-8
        smtp:
          write-timeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8
    verify:
      host: ${VERIFY_EMAIL_HOST}
  profiles:
    active: ${ACTIVE_PROFILE:test}
  jpa:
    open-in-view: false
server:
  port: ${SERVER_PORT}
api:
  security:
    jwt:
      secret: ${JWT_SECRET}

