#Database
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: my-fit-body
DB_USER: root
DB_PASSWORD: root

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: test

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true

