spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:my-fit-body}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true

