version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRES_DB=${DB_NAME:-my-fit-body}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_EMAIL:-admin@root.com}
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD:-root}
    depends_on:
      - db

volumes:
    postgres:
