version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRES_DB=${DB_NAME:-my-fit-body}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
  db_test:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRES_DB=${DB_NAME:-my-fit-body-test}
    volumes:
      - postgres_test:/data/postgres
    restart: unless-stopped

volumes:
    postgres:
    postgres_test:

